package com.qalab.qalabai.service.report;

import com.qalab.qalabai.service.workspace.TestArtifacts;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.List;
import java.util.Map;

/**
 * Renders a run as a single self-contained HTML file.
 *
 * <p>"Self-contained" is a requirement, not a nicety: the report has to survive being
 * attached to an email, dropped in a ticket, or archived on a machine with no network.
 * So there is no CDN, no web font, no external stylesheet — the CSS is inline and the
 * screenshots are base64 data URIs.</p>
 *
 * <p><strong>Videos and traces are linked, not embedded.</strong> They are routinely tens
 * of megabytes; base64 would inflate them by a third and produce an HTML file that
 * cannot be opened in a mail client. They sit next to the report in the same artifact
 * directory and are referenced relatively, so the report is still a single file to move
 * around — with the media directory alongside it. Screenshots, which are the thing a
 * reader actually looks at, are embedded.</p>
 *
 * <p>Screenshots above {@value #MAX_EMBEDDED_SCREENSHOT_BYTES} are linked rather than
 * embedded for the same reason, one file at a time.</p>
 */
public final class HtmlReportRenderer {

    /** 4 MB. Beyond this the base64 payload stops being worth inlining. */
    static final long MAX_EMBEDDED_SCREENSHOT_BYTES = 4L * 1024 * 1024;

    private HtmlReportRenderer() {
    }

    /**
     * @param summary  run-level counters and status
     * @param tests    per-test results, in run order
     * @param extras   optional sections (failure analysis, healing, test plan)
     * @return the complete HTML document
     */
    public static String render(Map<String, Object> summary,
                                List<TestCaseView> tests,
                                Map<String, Object> extras) {
        return render(summary, tests, extras, null);
    }

    /**
     * @param artifactDir directory the report is being written into. Attachment paths in
     *                    {@code tests} are relative to it, so screenshots can be
     *                    embedded and the rest linked without the report caring where
     *                    the run happened.
     */
    public static String render(Map<String, Object> summary,
                                List<TestCaseView> tests,
                                Map<String, Object> extras,
                                Path artifactDir) {
        StringBuilder out = new StringBuilder(64 * 1024);
        out.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        out.append("<meta charset=\"utf-8\">\n");
        out.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        out.append("<title>").append(esc(title(summary))).append("</title>\n");
        out.append("<style>\n").append(css()).append("</style>\n");
        out.append("</head>\n<body>\n");

        out.append("<header>\n<h1>").append(esc(title(summary))).append("</h1>\n");
        out.append("<p class=\"sub\">Generated by QALabAI</p>\n</header>\n");

        renderSummary(out, summary);
        renderTests(out, tests, artifactDir);
        renderExtras(out, extras);
        renderFooter(out, summary);

        out.append("</body>\n</html>\n");
        return out.toString();
    }

    // ---- sections ----

    private static void renderSummary(StringBuilder out, Map<String, Object> summary) {
        int passed = intOf(summary, "passed");
        int failed = intOf(summary, "failed");
        int skipped = intOf(summary, "skipped");
        int total = passed + failed + skipped;

        out.append("<section class=\"cards\">\n");
        card(out, "Total", String.valueOf(total), "neutral");
        card(out, "Passed", String.valueOf(passed), "pass");
        card(out, "Failed", String.valueOf(failed), failed > 0 ? "fail" : "neutral");
        card(out, "Skipped", String.valueOf(skipped), "neutral");
        if (total > 0) {
            card(out, "Pass rate", Math.round(passed * 100.0 / total) + "%",
                    failed == 0 ? "pass" : "fail");
        }
        if (summary.get("durationMs") != null) {
            card(out, "Duration", formatDuration(longOf(summary, "durationMs")), "neutral");
        }
        out.append("</section>\n");
    }

    private static void card(StringBuilder out, String label, String value, String tone) {
        out.append("<div class=\"card ").append(tone).append("\">")
                .append("<div class=\"card-value\">").append(esc(value)).append("</div>")
                .append("<div class=\"card-label\">").append(esc(label)).append("</div>")
                .append("</div>\n");
    }

    private static void renderTests(StringBuilder out, List<TestCaseView> tests, Path artifactDir) {
        out.append("<section>\n<h2>Tests</h2>\n");
        if (tests == null || tests.isEmpty()) {
            // Degrade rather than invent. Saying "no results" is honest; rendering an
            // empty green table would read as a passing run.
            out.append("<p class=\"empty\">This run produced no per-test results. ")
                    .append("The console output is below.</p>\n");
            return;
        }
        out.append("<table>\n<thead><tr>")
                .append("<th>Test</th><th>Status</th><th class=\"num\">Duration</th>")
                .append("<th>Retries</th><th>Evidence</th>")
                .append("</tr></thead>\n<tbody>\n");

        for (TestCaseView test : tests) {
            renderTestRow(out, test, artifactDir);
        }
        out.append("</tbody>\n</table>\n</section>\n");
    }

    private static void renderTestRow(StringBuilder out, TestCaseView test, Path artifactDir) {
        String status = test.status() == null ? "unknown" : test.status();
        out.append("<tr class=\"status-").append(esc(status)).append("\">");
        out.append("<td><div class=\"test-title\">").append(esc(nullSafe(test.title())))
                .append("</div>");
        if (test.file() != null && !test.file().isBlank()) {
            out.append("<div class=\"test-file\">").append(esc(test.file())).append("</div>");
        }
        if (test.errorMessage() != null && !test.errorMessage().isBlank()) {
            out.append("<details class=\"error\"><summary>")
                    .append(esc(firstLine(test.errorMessage())))
                    .append("</summary><pre>").append(esc(test.errorMessage())).append("</pre></details>");
        }
        if (test.snippet() != null && !test.snippet().isBlank()) {
            out.append("<details class=\"error\"><summary>Stack</summary><pre>")
                    .append(esc(test.snippet())).append("</pre></details>");
        }
        out.append("</td>");

        out.append("<td><span class=\"badge ").append(esc(status)).append("\">")
                .append(esc(status)).append("</span></td>");
        out.append("<td class=\"num\">").append(formatDuration(test.durationMs())).append("</td>");
        out.append("<td class=\"num\">").append(test.retries() > 0 ? String.valueOf(test.retries()) : "—")
                .append("</td>");
        out.append("<td>").append(evidenceCell(test, artifactDir)).append("</td>");
        out.append("</tr>\n");
    }

    /** Screenshots inline; trace and video as relative links into the artifact dir. */
    private static String evidenceCell(TestCaseView test, Path artifactDir) {
        StringBuilder sb = new StringBuilder();
        for (String screenshot : nullSafeList(test.screenshots())) {
            String embedded = embedImage(artifactDir, screenshot);
            if (embedded != null) {
                // The link points at the file, not at the data. Wrapping the image in an
                // anchor whose href is the same data URI would embed every screenshot
                // twice and double the size of the report for no benefit.
                sb.append("<a class=\"shot\" href=\"").append(esc(screenshot)).append("\">")
                        .append("<img src=\"").append(esc(embedded))
                        .append("\" alt=\"Screenshot of ").append(esc(nullSafe(test.title())))
                        .append("\" loading=\"lazy\"></a>");
            } else {
                sb.append("<a class=\"file\" href=\"").append(esc(screenshot))
                        .append("\">screenshot</a><br>");
            }
        }
        for (String video : nullSafeList(test.videos())) {
            sb.append("<a class=\"file\" href=\"").append(esc(video))
                    .append("\">video</a><br>");
        }
        for (String trace : nullSafeList(test.traces())) {
            sb.append("<a class=\"file\" href=\"").append(esc(trace))
                    .append("\">trace</a><br>");
        }
        return sb.isEmpty() ? "<span class=\"none\">—</span>" : sb.toString();
    }

    private static void renderExtras(StringBuilder out, Map<String, Object> extras) {
        if (extras == null) {
            return;
        }
        for (Map.Entry<String, Object> entry : extras.entrySet()) {
            Object value = entry.getValue();
            if (value == null) {
                continue;
            }
            if (value instanceof String text && !text.isBlank()) {
                out.append("<section>\n<h2>").append(esc(heading(entry.getKey()))).append("</h2>\n")
                        .append("<pre class=\"block\">").append(esc(text)).append("</pre>\n</section>\n");
            } else if (value instanceof Map<?, ?> map && !map.isEmpty()) {
                out.append("<section>\n<h2>").append(esc(heading(entry.getKey()))).append("</h2>\n<dl>\n");
                for (Map.Entry<?, ?> field : map.entrySet()) {
                    out.append("<dt>").append(esc(String.valueOf(field.getKey()))).append("</dt><dd>")
                            .append(esc(field.getValue() == null ? "—" : String.valueOf(field.getValue())))
                            .append("</dd>\n");
                }
                out.append("</dl>\n</section>\n");
            }
        }
    }

    private static void renderFooter(StringBuilder out, Map<String, Object> summary) {
        out.append("<footer>\n");
        appendMeta(out, "Execution", summary.get("executionId"));
        appendMeta(out, "Test file", summary.get("testFile"));
        appendMeta(out, "Status", summary.get("status"));
        appendMeta(out, "Created", summary.get("createdAt"));
        out.append("</footer>\n");
    }

    private static void appendMeta(StringBuilder out, String label, Object value) {
        if (value == null) {
            return;
        }
        out.append("<span><b>").append(esc(label)).append(":</b> ").append(esc(String.valueOf(value)))
                .append("</span>\n");
    }

    // ---- helpers ----

    /**
     * @return a {@code data:} URI for the image, or null when it should be linked
     *         instead — because it is missing, unreadable, not an image, or too large
     *         to be worth inlining
     */
    static String embedImage(Path artifactDir, String relativePath) {
        try {
            Path file = artifactDir == null ? Path.of(relativePath) : artifactDir.resolve(relativePath);
            if (!Files.isRegularFile(file)) {
                return null;
            }
            long size = Files.size(file);
            if (size == 0 || size > MAX_EMBEDDED_SCREENSHOT_BYTES) {
                return null;
            }
            String contentType = contentType(file.getFileName().toString().toLowerCase());
            if (contentType == null) {
                return null;
            }
            String encoded = Base64.getEncoder()
                    .encodeToString(Files.readAllBytes(file));
            return "data:" + contentType + ";base64," + encoded;
        } catch (IOException | RuntimeException e) {
            // A missing or unreadable screenshot must not take the whole report down.
            return null;
        }
    }

    private static String contentType(String fileName) {
        if (fileName.endsWith(".png")) {
            return "image/png";
        }
        if (fileName.endsWith(".jpg") || fileName.endsWith(".jpeg")) {
            return "image/jpeg";
        }
        if (fileName.endsWith(".gif")) {
            return "image/gif";
        }
        if (fileName.endsWith(".webp")) {
            return "image/webp";
        }
        return null;
    }

    /** One decimal place, but no trailing {@code .0}: "1 s" reads better than "1.0 s". */
    private static String trim(double value) {
        String text = String.valueOf(Math.round(value * 10) / 10.0);
        return text.endsWith(".0") ? text.substring(0, text.length() - 2) : text;
    }

    static String formatDuration(Long ms) {
        if (ms == null) {
            return "—";
        }
        if (ms < 1000) {
            return ms + " ms";
        }
        double seconds = ms / 1000.0;
        if (seconds < 60) {
            return trim(seconds) + " s";
        }
        long minutes = (long) (seconds / 60);
        return minutes + "m " + trim(seconds - minutes * 60) + "s";
    }

    private static String title(Map<String, Object> summary) {
        Object file = summary.get("testFile");
        return file == null ? "Test run report" : "Test run — " + file;
    }

    private static String heading(String key) {
        String spaced = key.replaceAll("([a-z])([A-Z])", "$1 $2");
        return Character.toUpperCase(spaced.charAt(0)) + spaced.substring(1);
    }

    private static String firstLine(String text) {
        int newline = text.indexOf('\n');
        String line = newline < 0 ? text : text.substring(0, newline);
        return line.length() > 160 ? line.substring(0, 160) + "…" : line;
    }

    private static int intOf(Map<String, Object> map, String key) {
        Object value = map.get(key);
        return value instanceof Number n ? n.intValue() : 0;
    }

    private static long longOf(Map<String, Object> map, String key) {
        Object value = map.get(key);
        return value instanceof Number n ? n.longValue() : 0L;
    }

    private static String nullSafe(String value) {
        return value == null ? "" : value;
    }

    private static List<String> nullSafeList(List<String> values) {
        return values == null ? List.of() : values;
    }

    /**
     * Escapes for both element text and quoted attribute values. Without the quote
     * handling, a test title containing a double quote would break out of an attribute —
     * and a test title is model-generated text, so it can contain anything.
     */
    static String esc(String value) {
        if (value == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder(value.length() + 16);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '&' -> sb.append("&amp;");
                case '<' -> sb.append("&lt;");
                case '>' -> sb.append("&gt;");
                case '"' -> sb.append("&quot;");
                case '\'' -> sb.append("&#39;");
                default -> sb.append(c);
            }
        }
        return sb.toString();
    }

    /** One row of the results table. */
    public record TestCaseView(
            int ordinal,
            String file,
            String title,
            String status,
            Long durationMs,
            int retries,
            String errorMessage,
            String snippet,
            List<String> screenshots,
            List<String> videos,
            List<String> traces
    ) {
        public static TestCaseView from(TestArtifacts artifacts) {
            return new TestCaseView(artifacts.ordinal(), artifacts.testFile(), artifacts.title(),
                    artifacts.status(), null, 0, null, null,
                    artifacts.screenshots(), artifacts.videos(), artifacts.traces());
        }
    }

    private static String css() {
        return """
                *{box-sizing:border-box}
                body{margin:0;padding:2rem 1.5rem 4rem;font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#1a1d21;background:#f6f7f9}
                header{max-width:1100px;margin:0 auto 1.5rem}
                h1{margin:0;font-size:1.6rem;letter-spacing:-.01em}
                h2{margin:0 0 .75rem;font-size:1.15rem}
                .sub{margin:.25rem 0 0;color:#6b7280;font-size:.9rem}
                section{max-width:1100px;margin:0 auto 2rem;background:#fff;border:1px solid #e3e6ea;border-radius:10px;padding:1.25rem 1.5rem}
                .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:.75rem;margin:0 auto 2rem;max-width:1100px}
                .card{background:#fff;border:1px solid #e3e6ea;border-radius:10px;padding:.9rem 1rem}
                .card-value{font-size:1.5rem;font-weight:650;letter-spacing:-.02em}
                .card-label{color:#6b7280;font-size:.8rem;text-transform:uppercase;letter-spacing:.05em;margin-top:.15rem}
                .card.pass .card-value{color:#0f7b41}
                .card.fail .card-value{color:#b42318}
                table{width:100%;border-collapse:collapse}
                th,td{text-align:left;padding:.6rem .5rem;border-bottom:1px solid #eef0f3;vertical-align:top}
                th{font-size:.78rem;text-transform:uppercase;letter-spacing:.04em;color:#6b7280;border-bottom:1px solid #e3e6ea}
                td.num,th.num{text-align:right;white-space:nowrap}
                .test-title{font-weight:550}
                .test-file{color:#6b7280;font-size:.85rem;margin-top:.15rem}
                .badge{display:inline-block;padding:.1rem .5rem;border-radius:999px;font-size:.75rem;font-weight:600;text-transform:uppercase;letter-spacing:.03em}
                .badge.passed{background:#e6f4ec;color:#0f7b41}
                .badge.failed{background:#fdecea;color:#b42318}
                .badge.skipped{background:#eef0f3;color:#5b6472}
                .badge.unknown{background:#fff4e5;color:#8a5300}
                tr.status-failed{background:#fffbfb}
                details.error{margin-top:.4rem}
                details.error summary{cursor:pointer;color:#b42318;font-size:.85rem;outline:none}
                pre.block,details.error pre{margin:.5rem 0 0;padding:.7rem .8rem;background:#f6f7f9;border:1px solid #e3e6ea;border-radius:6px;overflow-x:auto;font:12.5px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word}
                dl{margin:0;display:grid;grid-template-columns:max-content 1fr;gap:.3rem .9rem}
                dt{color:#6b7280;font-size:.9rem}
                dd{margin:0}
                .shot{display:inline-block;margin:0 .4rem .4rem 0}
                .shot img{max-width:190px;max-height:130px;border:1px solid #e3e6ea;border-radius:6px;display:block}
                a.file{font-size:.82rem;color:#1a56c4;text-decoration:none;border-bottom:1px solid #c9d6ef}
                a.file:hover{text-decoration:underline}
                .none,.empty{color:#9aa2ae}
                footer{max-width:1100px;margin:0 auto;color:#6b7280;font-size:.85rem;display:flex;flex-wrap:wrap;gap:1rem}
                """;
    }
}
