-- Baseline schema for QALabAI (B-014).
--
-- Derived from the JPA entities using the PostgreSQL dialect rather than written by
-- hand, so it cannot silently disagree with the model at the moment it was captured.
-- It is then verified continuously: with ddl-auto=validate the application refuses to
-- start if this file and the entities drift apart, which turns the baseline into a
-- checked contract rather than a snapshot nobody reads.
--
-- From here on the schema changes ONLY through new versioned migrations. Never edit
-- this file, and never rely on Hibernate to alter a table.
--
-- Note: locator_observation.element_identity_json is TEXT. It was previously @Lob,
-- which PostgreSQL maps to `oid` (a large-object reference) rather than text.


create table account (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    budget_policy varchar(10) not null check (budget_policy in ('HARD','SOFT','NONE')),
    plan varchar(20) not null check (plan in ('FREE','PRO','TEAM')),
    name varchar(255) not null unique,
    primary key (id)
);

create table ai_usage_record (
    estimated boolean not null,
    estimated_cost numeric(18,8),
    input_tokens integer not null,
    output_tokens integer not null,
    total_tokens integer not null,
    account_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint,
    credential_mode varchar(20) not null check (credential_mode in ('MANAGED','BYOK','LOCAL')),
    provider varchar(30) not null check (provider in ('AIQALAB','OPENAI','ANTHROPIC','GOOGLE','OPENCODE','OLLAMA')),
    operation varchar(40) not null check (operation in ('EXPLORE','ANALYZE','LOCATOR_GENERATION','TEST_PLAN','TEST_GENERATION','FAILURE_ANALYSIS','SELF_HEALING','HEALING_EVALUATION','BUG_REPORT','FULL_WORKFLOW')),
    model varchar(255),
    operation_id varchar(255),
    primary key (id)
);

create table api_key (
    account_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_used_at timestamp(6),
    revoked_at timestamp(6),
    key_hash varchar(64) not null,
    salt varchar(64) not null,
    label varchar(120) not null,
    primary key (id),
    constraint idx_api_key_hash unique (key_hash)
);

create table bug_report (
    created_at timestamp(6) not null,
    execution_id bigint,
    id bigint generated by default as identity,
    project_id bigint,
    failure_type varchar(50),
    severity varchar(50),
    affected_element varchar(300),
    title varchar(300),
    actual_behavior TEXT,
    console_logs_excerpt TEXT,
    error_message TEXT,
    expected_behavior TEXT,
    instruction TEXT,
    report_id varchar(255) not null unique,
    report_json TEXT,
    status varchar(255),
    steps_to_reproduce TEXT,
    suggested_fix TEXT,
    summary TEXT,
    test_file varchar(255),
    test_name varchar(255),
    primary key (id)
);

create table failure_analysis (
    confidence integer,
    healing_candidate boolean,
    created_at timestamp(6) not null,
    execution_id bigint not null,
    id bigint generated by default as identity,
    project_id bigint not null,
    summary varchar(2000),
    analysis_json varchar(5000),
    affected_element varchar(255),
    failure_type varchar(255) not null,
    primary key (id)
);

create table failure_history (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint not null,
    message varchar(2000),
    failure_type varchar(255) not null,
    related_element varchar(255),
    test_name varchar(255) not null,
    primary key (id)
);

create table generated_test (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint,
    page_object_code TEXT,
    page_url TEXT not null,
    scenario_name TEXT not null,
    test_code TEXT not null,
    test_file_name varchar(255),
    test_type varchar(255),
    primary key (id)
);

create table healing_proposal (
    confidence float(53) not null,
    original_locator_stability float(53),
    recommended_locator_stability float(53),
    recommended_quality_score float(53),
    recommended_semantic_score float(53),
    safe_to_apply boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint,
    reviewed_at timestamp(6),
    proposal_id varchar(64) not null unique,
    original_locator varchar(500) not null,
    recommended_locator varchar(500) not null,
    reason varchar(2000),
    alternatives_json TEXT,
    classification varchar(255) not null,
    confidence_label varchar(255) not null,
    original_locator_health varchar(255),
    recommended_locator_health varchar(255),
    recommended_stability_level varchar(255),
    review_action varchar(255),
    run_id varchar(255),
    status varchar(255) not null,
    test_id varchar(255),
    test_name varchar(255),
    primary key (id)
);

create table healing_suggestion (
    confidence integer,
    approved_at timestamp(6),
    created_at timestamp(6) not null,
    execution_id bigint not null,
    failure_analysis_id bigint,
    id bigint generated by default as identity,
    project_id bigint not null,
    new_locator varchar(500) not null,
    old_locator varchar(500) not null,
    reason varchar(1000),
    approved_by varchar(255),
    element_name varchar(255) not null,
    status varchar(255) not null,
    primary key (id)
);

create table locator_definition (
    confidence integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    preferred_locator varchar(500) not null,
    reason varchar(1000),
    fallback_locators varchar(2000),
    element_name varchar(255) not null,
    element_type varchar(255) not null,
    page_url varchar(255) not null,
    strategy varchar(255) not null,
    primary key (id)
);

create table locator_history (
    confidence integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_successful_execution timestamp(6),
    project_id bigint not null,
    locator varchar(500) not null,
    element_name varchar(255) not null,
    status varchar(255) not null,
    strategy varchar(255),
    primary key (id)
);

create table locator_observation (
    score float(53) not null,
    semantic_score float(53) not null,
    stability_score float(53) not null,
    uniqueness float(53) not null,
    id bigint generated by default as identity,
    observed_at timestamp(6) not null,
    project_id bigint,
    element_fingerprint varchar(128) not null,
    locator varchar(512) not null,
    page_url varchar(2048) not null,
    element_identity_json TEXT,
    execution_id varchar(255),
    health varchar(255) not null,
    status varchar(255) not null,
    strategy varchar(255) not null,
    primary key (id)
);

create table page_analysis_history (
    version integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint not null,
    analysis_json varchar(10000),
    page_type varchar(255),
    screenshot_reference varchar(255),
    url varchar(255) not null,
    primary key (id)
);

create table project (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    description varchar(1000),
    base_url varchar(255) not null,
    framework varchar(255) not null,
    name varchar(255) not null,
    repository_url varchar(255) not null,
    workspace_path varchar(255),
    primary key (id)
);

create table test_execution (
    created_at timestamp(6) not null,
    duration bigint,
    id bigint generated by default as identity,
    project_id bigint,
    console_logs TEXT,
    error_message TEXT,
    report_path varchar(255),
    screenshot_path varchar(255),
    status varchar(255) not null,
    test_file varchar(255) not null,
    trace_path varchar(255),
    video_path varchar(255),
    primary key (id)
);

create table test_plan (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint,
    page_type varchar(255) not null,
    page_url varchar(255) not null,
    primary key (id)
);

create table test_scenario (
    id bigint generated by default as identity,
    test_plan_id bigint not null,
    description varchar(1000),
    name varchar(255) not null,
    priority varchar(255) not null,
    type varchar(255) not null,
    primary key (id)
);

create table test_scenario_elements (
    scenario_id bigint not null,
    element_name varchar(200)
);

create table test_scenario_steps (
    step_order integer not null,
    scenario_id bigint not null,
    step varchar(500),
    primary key (step_order, scenario_id)
);

-- Foreign keys

alter table if exists test_scenario add constraint FKmc73jwsjb4b3pmv480i8h97i0 foreign key (test_plan_id) references test_plan;

alter table if exists test_scenario_elements add constraint FKrwo9vj3xlif9rh039n9btxyut foreign key (scenario_id) references test_scenario;

alter table if exists test_scenario_steps add constraint FK440whwo50sfok1pn850f7cc5s foreign key (scenario_id) references test_scenario;

-- Indexes

create index idx_locator_observation_lookup on locator_observation (project_id, element_fingerprint, observed_at);
