/**
 * Shared action lifecycle model for the whole UI.
 *
 * Every meaningful user action follows the same lifecycle:
 * IDLE → STARTING → RUNNING → COMPLETED | FAILED
 * and the UI renders the same reusable feedback for all of them.
 */

export type ActionStatus = "idle" | "starting" | "running" | "completed" | "failed";

export type StepStatus = "pending" | "active" | "done" | "error";

export interface ActionStep {
  name: string;
  status: StepStatus;
}

export interface ActivityEntry {
  time: number;
  message: string;
  tone: "neutral" | "success" | "error";
}

export interface TokenUsage {
  used: number;
  limit: number;
  remaining: number;
  exhausted?: boolean;
}

export interface ActionError {
  code: string;
  message: string;
  friendlyLabel: string;
  operationId?: string | null;
  status?: number;
  /** Whether this failure signals an AI fallback path (budget/provider). */
  aiFallback?: boolean;
}

export interface ActionState {
  id: string;
  /** Short title, e.g. "Analyze". */
  name: string;
  /** Verb phrase shown while running, e.g. "Analyzing project...". */
  label: string;
  status: ActionStatus;
  /** Name of the current phase (human readable). */
  currentStep: string;
  /** Ordered phase timeline. */
  steps: ActionStep[];
  /** Live user-facing activity log. */
  activity: ActivityEntry[];
  startedAt: number;
  completedAt?: number;
  durationMs?: number;
  error?: ActionError;
  /** Arbitrary payload produced by the operation. */
  result?: unknown;
  /** Whether this operation uses AI at all. */
  aiUsed?: boolean;
  /** True when AI could not run and the pipeline continued deterministically. */
  aiUnavailable?: boolean;
  tokenUsage?: TokenUsage;
  /** Id generated by the backend (op-...), when the operation provides one. */
  operationId?: string | null;
  /** Extra metadata surfaced in the header (target url, execution id...). */
  meta?: Record<string, string>;
}

export interface ActionSnapshot {
  id: string;
  name: string;
  status: ActionStatus;
  errorMessage?: string;
  startedAt: number;
  durationMs?: number;
  result?: unknown;
  operationId?: string | null;
}

export type ActionUpdate = Partial<Pick<ActionState,
  | "status"
  | "label"
  | "currentStep"
  | "steps"
  | "activity"
  | "error"
  | "result"
  | "completedAt"
  | "durationMs"
  | "aiUsed"
  | "aiUnavailable"
  | "tokenUsage"
  | "operationId"
  | "meta">>;

export interface RunActionOptions {
  /** True when the operation is known to involve an AI call. */
  aiUsed?: boolean;
  /** Estimated phase timeline for operations whose backend cannot stream progress. */
  steps?: string[];
}

/** Result descriptor used by ActionProgress to render a compact summary. */
export interface ActionResultSummary {
  title: string;
  statusLabel: string;
  lines: { label: string; value: string }[];
  actions?: { label: string; onClick: () => void; variant?: "default" | "outline" | "destructive" }[];
}
